### ISSUE TITLE
result of png is very large in size

### ISSUE THREAD

**Issue by amitm02** [galfar/deskew#24]

**Comment by amitm02** [comment]
I have a PNG file size 93.56kb (1694x2245)
The output PNG is of size 1312.64kb.
Is there a way to keep the compression size of the image so it won't get inflated?

**Comment by galfar** [comment]
Is your PNG by any chance 1bit color?
In that case Deskew saved the output as 8bit to not lose image detail created during rotation.
You can force the output to be 1bit by adding **-f b1** to command line when calling Deskew.

**Comment by amitm02** [comment]
no, 
it turns out there are many png engines with different optimisations.
I think what is used by deskew is just a not very efficient one.
I've ended up repack the image with one of those: https://css-ig.net/png-tools-overview

**Comment by Ortega-Dan** [comment]
This repo is gret, but I include that I am working with grayscale png images and in my case those are in average going from 500K to 1.2M
![image](https://user-images.githubusercontent.com/24926168/78200804-5b3d2f00-7455-11ea-952d-da65a14b901b.png)
