### ISSUE TITLE
Support for multipage pdf files

### ISSUE THREAD

**Issue by cristobaltapia** [galfar/deskew#25]
Hi, thanks for this program.
I think it would be useful to support to deskew a whole pdf file with multiple pages. I normally scan books or documents directly into a multipage pdf file, since it is more manageable to only have one file and not one per page. Do you think that this might be within the scope of this program?

Cheers

**Comment by galfar** [comment]
Hi, 
PDF support inside Deskew would need to rely on some external tools 
to convert between images and PDF anyway.

Here's a script that does exactly this (single PDF -> images -> single PDF) using deskew and ImageMagick:
https://gist.github.com/garrettheaver/9375deebb0023bfd8937

**Comment by cristobaltapia** [comment]
Oh, that's cool! Thanks a lot!
