### ISSUE TITLE
Compiling the GUI on Linux?

### ISSUE THREAD

**Issue by ctrlcctrlv** [galfar/deskew#37]
Hello @galfar, I'm your AUR maintainer

I noticed you have a GUI now, but in Scripts there only seems to be a script to compile it on Mac.

I get:

```
deskewgui.lpr(10,3) Fatal: Can't find unit Interfaces used by deskewgui
```

Is this usable on Linux?

**Comment by galfar** [comment]
Hello, 
yes it works on Linux, it needs Lazarus to build though. 
Just call `lazbuild --build-mode=Release "Gui/deskewgui.lpi` in package root dir
(as used in https://github.com/galfar/deskew/blob/master/.github/workflows/ci.yml).
