### ISSUE TITLE
Please clarify licensing situation

### ISSUE THREAD

**Issue by ctrlcctrlv** [galfar/deskew#38]
README says that the license is MIT, but the source files seem to all claim MPL/LGPL. What is actual license of this code? Can you please distribute a license file?

This came up at AUR: https://aur.archlinux.org/packages/deskew-git/

**Comment by ctrlcctrlv** [comment]
Hello?

**Comment by micwoj92** [comment]
Hi

**Comment by ctrlcctrlv** [comment]
Clarify the licensing situation or I'm going to have to drop this from the AUR I'm afraid.

**Comment by galfar** [comment]
I'll get it sorted out this week, the library dependency used for image stuff is MPL/LGPL. the rest should not be.

**Comment by galfar** [comment]
Deskew specific stuff is now MPL 2.0, notices in sources were updated and LICENSE file is also included.
Code in Imaging folder which has MPL/LGPL notices is a separate library and will be replaced with git submodule.
