### ISSUE TITLE
GUI: Option to select sampling filter

### ISSUE THREAD

**Issue by uranuspucksaxophone** [galfar/deskew#46]
The GUI does not currently have an option for this, and I don't know any other way of doing batch image processing with the CLI tool, the default linear filter option blurs the images too much, so it would be nice to be able to change it in the GUI.

**Comment by galfar** [comment]
This is already implemented, look in *Advance Options* dialog.
The latest binary builds can be found here: https://github.com/galfar/deskew/actions/runs/2548373070
(in *Artifacts* section).
