### ISSUE TITLE
Bug - -c tg4 seems to incorrectly compress with LZW in windows CLI

### ISSUE THREAD

**Issue by theretrobristolian** [galfar/deskew#54]
Hey,

I really love the product and am finding it very useful, but I 'think' I've found a bug. the below command compresses in LZW:

deskew.exe -t a -a 10 -b FFFFFF -c tg4 -o C:\IT\Deskewed\MS9-29\MS9-29_page_0007.tif C:\IT\Extracted\MS9-29\MS9-29_page_0007.tif

The input file is compressed with CCITT T.6 so I would expect this to work I believe.

Thanks,

David

**Comment by galfar** [comment]
Hi, 

for now you can add `-f b1` argument to force pixel format conversion to 1 bit before saving the output. 
For rotations after skew detection the program needs to convert to 8 bits per channel (for filtered rotation etc.). When writing the output TIFF it sees G4 would not fit and uses default encoding for 8 bit data.
Makes sense to convert back to binary when G4/CCITT is explicitly requested - user knows what to expect :)

Marek

**Comment by galfar** [comment]
Fixed
