### ISSUE TITLE
No more libtiff5 on Debian

### ISSUE THREAD

**Issue by Opisek** [galfar/deskew#60]
My image processing pipeline seems to have broken recently and I narrowed the issue down to deskew.

It appeared that, no matter which `.tif` file I try to deskew, I got the following error
```
EImagingError: Error while loading images from file "./xyz.tif" (file format: tif). Exception Message: Invalid floating point operation
```

After uninstalling my `libtiff` wanting to reinstall it, I realized that `libtiff5` is no longer available on Debian.

I tried installing `libtiff6` and `libtiff5-dev` instead, but both give me the following error:
```
Deskew 1.30 (2019-06-07) x64 by Marek Mauder
http://galfar.vevb.net/deskew/

Error: File format not supported: ./xyz.tif
```

I also tried creating a symlink from `libtiff.so.5` to `libtiff.so.6`, and this puts me back at the start:
```
EImagingError: Error while loading images from file "./xyz.tif" (file format: tif). Exception Message: Invalid floating point operation
```

What can I do now?

**Comment by Opisek** [comment]
Seems after all those tries, all it took was rebooting my server. Apologies for the notification!

**Comment by galfar** [comment]
No problem. I need to anyway update the libtiff loader in Deskew as it looks for `libtiff.so.5` directly, so I'll probably drop the version number there and let it load any libtiff in the system.
I think I added it there like 10 years ago when libtiff4 vs libtiff5 had some breaking changes,
now with libtiff5 and libtiff6 it should be fine.
